# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import entity_platform_pb2 as entity__platform__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in entity_platform_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EntityPlatformInterceptorStub(object):
    """-------------------------
    gRPC contract
    -------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlatformSetup = channel.unary_unary(
                '/hacore.EntityPlatformInterceptor/PlatformSetup',
                request_serializer=entity__platform__pb2.PlatformSetupRequest.SerializeToString,
                response_deserializer=entity__platform__pb2.PlatformSetupResponse.FromString,
                _registered_method=True)
        self.PlatformReset = channel.unary_unary(
                '/hacore.EntityPlatformInterceptor/PlatformReset',
                request_serializer=entity__platform__pb2.PlatformResetRequest.SerializeToString,
                response_deserializer=entity__platform__pb2.PlatformResetResponse.FromString,
                _registered_method=True)
        self.EntitiesAdded = channel.unary_unary(
                '/hacore.EntityPlatformInterceptor/EntitiesAdded',
                request_serializer=entity__platform__pb2.EntitiesAddedRequest.SerializeToString,
                response_deserializer=entity__platform__pb2.EntitiesAddedResponse.FromString,
                _registered_method=True)
        self.EntityAdded = channel.unary_unary(
                '/hacore.EntityPlatformInterceptor/EntityAdded',
                request_serializer=entity__platform__pb2.EntityAddedRequest.SerializeToString,
                response_deserializer=entity__platform__pb2.EntityAddedResponse.FromString,
                _registered_method=True)
        self.EntityRemoved = channel.unary_unary(
                '/hacore.EntityPlatformInterceptor/EntityRemoved',
                request_serializer=entity__platform__pb2.EntityRemovedRequest.SerializeToString,
                response_deserializer=entity__platform__pb2.EntityRemovedResponse.FromString,
                _registered_method=True)
        self.EntityUpdateTick = channel.unary_unary(
                '/hacore.EntityPlatformInterceptor/EntityUpdateTick',
                request_serializer=entity__platform__pb2.EntityUpdateTickRequest.SerializeToString,
                response_deserializer=entity__platform__pb2.EntityUpdateTickResponse.FromString,
                _registered_method=True)
        self.RegisterEntityService = channel.unary_unary(
                '/hacore.EntityPlatformInterceptor/RegisterEntityService',
                request_serializer=entity__platform__pb2.RegisterEntityServiceRequest.SerializeToString,
                response_deserializer=entity__platform__pb2.RegisterEntityServiceResponse.FromString,
                _registered_method=True)
        self.ExtractEntities = channel.unary_unary(
                '/hacore.EntityPlatformInterceptor/ExtractEntities',
                request_serializer=entity__platform__pb2.ExtractEntitiesRequest.SerializeToString,
                response_deserializer=entity__platform__pb2.ExtractEntitiesResponse.FromString,
                _registered_method=True)


class EntityPlatformInterceptorServicer(object):
    """-------------------------
    gRPC contract
    -------------------------
    """

    def PlatformSetup(self, request, context):
        """Platform lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlatformReset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EntitiesAdded(self, request, context):
        """Entities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EntityAdded(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EntityRemoved(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EntityUpdateTick(self, request, context):
        """Update loop
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterEntityService(self, request, context):
        """Services
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EntityPlatformInterceptorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlatformSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.PlatformSetup,
                    request_deserializer=entity__platform__pb2.PlatformSetupRequest.FromString,
                    response_serializer=entity__platform__pb2.PlatformSetupResponse.SerializeToString,
            ),
            'PlatformReset': grpc.unary_unary_rpc_method_handler(
                    servicer.PlatformReset,
                    request_deserializer=entity__platform__pb2.PlatformResetRequest.FromString,
                    response_serializer=entity__platform__pb2.PlatformResetResponse.SerializeToString,
            ),
            'EntitiesAdded': grpc.unary_unary_rpc_method_handler(
                    servicer.EntitiesAdded,
                    request_deserializer=entity__platform__pb2.EntitiesAddedRequest.FromString,
                    response_serializer=entity__platform__pb2.EntitiesAddedResponse.SerializeToString,
            ),
            'EntityAdded': grpc.unary_unary_rpc_method_handler(
                    servicer.EntityAdded,
                    request_deserializer=entity__platform__pb2.EntityAddedRequest.FromString,
                    response_serializer=entity__platform__pb2.EntityAddedResponse.SerializeToString,
            ),
            'EntityRemoved': grpc.unary_unary_rpc_method_handler(
                    servicer.EntityRemoved,
                    request_deserializer=entity__platform__pb2.EntityRemovedRequest.FromString,
                    response_serializer=entity__platform__pb2.EntityRemovedResponse.SerializeToString,
            ),
            'EntityUpdateTick': grpc.unary_unary_rpc_method_handler(
                    servicer.EntityUpdateTick,
                    request_deserializer=entity__platform__pb2.EntityUpdateTickRequest.FromString,
                    response_serializer=entity__platform__pb2.EntityUpdateTickResponse.SerializeToString,
            ),
            'RegisterEntityService': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEntityService,
                    request_deserializer=entity__platform__pb2.RegisterEntityServiceRequest.FromString,
                    response_serializer=entity__platform__pb2.RegisterEntityServiceResponse.SerializeToString,
            ),
            'ExtractEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractEntities,
                    request_deserializer=entity__platform__pb2.ExtractEntitiesRequest.FromString,
                    response_serializer=entity__platform__pb2.ExtractEntitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hacore.EntityPlatformInterceptor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hacore.EntityPlatformInterceptor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EntityPlatformInterceptor(object):
    """-------------------------
    gRPC contract
    -------------------------
    """

    @staticmethod
    def PlatformSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hacore.EntityPlatformInterceptor/PlatformSetup',
            entity__platform__pb2.PlatformSetupRequest.SerializeToString,
            entity__platform__pb2.PlatformSetupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlatformReset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hacore.EntityPlatformInterceptor/PlatformReset',
            entity__platform__pb2.PlatformResetRequest.SerializeToString,
            entity__platform__pb2.PlatformResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EntitiesAdded(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hacore.EntityPlatformInterceptor/EntitiesAdded',
            entity__platform__pb2.EntitiesAddedRequest.SerializeToString,
            entity__platform__pb2.EntitiesAddedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EntityAdded(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hacore.EntityPlatformInterceptor/EntityAdded',
            entity__platform__pb2.EntityAddedRequest.SerializeToString,
            entity__platform__pb2.EntityAddedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EntityRemoved(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hacore.EntityPlatformInterceptor/EntityRemoved',
            entity__platform__pb2.EntityRemovedRequest.SerializeToString,
            entity__platform__pb2.EntityRemovedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EntityUpdateTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hacore.EntityPlatformInterceptor/EntityUpdateTick',
            entity__platform__pb2.EntityUpdateTickRequest.SerializeToString,
            entity__platform__pb2.EntityUpdateTickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterEntityService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hacore.EntityPlatformInterceptor/RegisterEntityService',
            entity__platform__pb2.RegisterEntityServiceRequest.SerializeToString,
            entity__platform__pb2.RegisterEntityServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hacore.EntityPlatformInterceptor/ExtractEntities',
            entity__platform__pb2.ExtractEntitiesRequest.SerializeToString,
            entity__platform__pb2.ExtractEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
