# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import event_interceptor_pb2 as event__interceptor__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in event_interceptor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventInterceptorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InterceptEvent = channel.unary_unary(
                '/hacore.EventInterceptor/InterceptEvent',
                request_serializer=event__interceptor__pb2.EventMessage.SerializeToString,
                response_deserializer=event__interceptor__pb2.EventResponse.FromString,
                _registered_method=True)


class EventInterceptorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InterceptEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventInterceptorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InterceptEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.InterceptEvent,
                    request_deserializer=event__interceptor__pb2.EventMessage.FromString,
                    response_serializer=event__interceptor__pb2.EventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hacore.EventInterceptor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hacore.EventInterceptor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventInterceptor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InterceptEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hacore.EventInterceptor/InterceptEvent',
            event__interceptor__pb2.EventMessage.SerializeToString,
            event__interceptor__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
