# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_interceptor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'event_interceptor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65vent_interceptor.proto\x12\x06hacore\"\\\n\x0c\x45ventMessage\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x11\n\tjson_data\x18\x03 \x01(\t\x12\x12\n\ncontext_id\x18\x04 \x01(\t\" \n\rEventResponse\x12\x0f\n\x07handled\x18\x01 \x01(\x08\x32Q\n\x10\x45ventInterceptor\x12=\n\x0eInterceptEvent\x12\x14.hacore.EventMessage\x1a\x15.hacore.EventResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_interceptor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTMESSAGE']._serialized_start=35
  _globals['_EVENTMESSAGE']._serialized_end=127
  _globals['_EVENTRESPONSE']._serialized_start=129
  _globals['_EVENTRESPONSE']._serialized_end=161
  _globals['_EVENTINTERCEPTOR']._serialized_start=163
  _globals['_EVENTINTERCEPTOR']._serialized_end=244
# @@protoc_insertion_point(module_scope)
