# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state_interceptor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'state_interceptor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17state_interceptor.proto\x12\x06hacore\"b\n\x11StateWriteRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x17\n\x0f\x61ttributes_json\x18\x03 \x01(\t\x12\x12\n\ncontext_id\x18\x04 \x01(\t\"_\n\x12StateWriteResponse\x12\x0f\n\x07handled\x18\x01 \x01(\x08\x12\x16\n\x0eoverride_state\x18\x02 \x01(\t\x12 \n\x18override_attributes_json\x18\x03 \x01(\t2`\n\x10StateInterceptor\x12L\n\x13InterceptStateWrite\x12\x19.hacore.StateWriteRequest\x1a\x1a.hacore.StateWriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_interceptor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATEWRITEREQUEST']._serialized_start=35
  _globals['_STATEWRITEREQUEST']._serialized_end=133
  _globals['_STATEWRITERESPONSE']._serialized_start=135
  _globals['_STATEWRITERESPONSE']._serialized_end=230
  _globals['_STATEINTERCEPTOR']._serialized_start=232
  _globals['_STATEINTERCEPTOR']._serialized_end=328
# @@protoc_insertion_point(module_scope)
